### ISSUE TITLE
Invalid object name "dbo.Players"

### ISSUE THREAD

**Issue by crannnabethadh** [miguel-jesus/ClickyCratesApi#1]
No se porqué pero me salta una excepción cuando intento registrar a un usuario.
![image](https://user-images.githubusercontent.com/55758822/83749176-93363d80-a663-11ea-9728-6ee8507585ed.png)
![image](https://user-images.githubusercontent.com/55758822/83749243-b103a280-a663-11ea-82ef-95c071433403.png)
La tabla Players de la base de datos la he creado bien con el nuevo script que has puesto.
![image](https://user-images.githubusercontent.com/55758822/83749343-d8f30600-a663-11ea-93e0-73168fbbf201.png)
Pero no se inserta el Player en la tabla de la BBDD.
He estado mirando y no se que pasa.
Alguna pista?

**Comment by crannnabethadh** [comment]
label:bug

**Comment by miguel-jesus** [comment]
Lo único que se me ocurre es , si has clonado de nuevo todo el repositorio , es que yo por ejemplo actualice el archivo web config y le añadi este nombre,quizás tienes otra base de datos con este nombre
![image](https://user-images.githubusercontent.com/56606006/83760979-f92bc080-a675-11ea-9900-9c8efb7e1abf.png)

**Comment by crannnabethadh** [comment]
Si era eso. Ya lo averigüé
